osx_image: xcode10.1
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods
- pod repo update
- pod install --project-directory=Example
- xcodebuild -showsdks
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/com.awareframework.ios.sensor.connectivity.xcworkspace -scheme com.awareframework.ios.sensor.connectivity-Example -sdk iphonesimulator12.1 -destination OS=12.1,name="iPhone 7" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO -allowProvisioningUpdates | xcpretty -c
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/com.awareframework.ios.sensor.connectivity.xcworkspace -scheme com.awareframework.ios.sensor.connectivity-Example -sdk iphonesimulator12.1 -destination OS=12.1,name="iPhone X" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO -allowProvisioningUpdates | xcpretty -c
deploy:
  provider: script
  script: "./scripts/release.sh"
  on:
    tags: true
after_success:
- echo 'success!'
env:
  global:
  - secure: E+kR/K5ajgCC+aLQUW8zwyGx1mi5yxFCADrNlAeOQ0kCjc9BxVdfWC4ypxoKgOcUceLGuqtwKj50fYjh4eCxCMUqCNGTlVGLImaLXocsvhbEzYJ0bShzT4AX8nUYwi508DJ36dc4J7XTn0M5QYB4Jcx9/hnHT4sWqfOE3IDvE33QGYc/d85uurAyzUnbuwHcihiOeTxiM0+cKRhvJfpHfI//1LbBV7JNgGbQdLm6EGlcF364U7WbErvOB90LB9fNaHQP0tH/a04F4ZzOaIwlMIz3lOLYcYp5EqLJRmPKbW8J4mt5D0kp21EtOUXycphbXmrUPZQ0E3GP7VNQP304hYsE8uTI01sRUeOCQPdPEn/gXexTa0KtoHmeEHwAW0sG04Ap7O/nbh523m/Xbij++R5Nx+6LQaaCyn4Qj8qhLBBBj7RAYPjiywysOYzPTEwa510royjoyU0l7pFKRzFhISKSHMbQtuxsFJ1pWV7xZQR/ZNcCiSQN1w3o0tnzXm7sJtzgaHNvRbmpl1zfLDEw6gwEHRQyq5b8QLkF/5FGBOwVZoR/1L7X0Bk7C8RbUqkgxsHeMrXmVXzksnCLM1yuBX2jOqx+bd5upgqbZUGsrkVj4B1P/BSPoCi24wQWY9buZdKwSRemA4oqImViWu6VJ8vbnz47ixVqMJLTxRxF1/g=
notifications:
  slack:
    secure: q6B+zftQWzUYe1G1Y6HDJIcl40n2G0duhtS82H4AywYFjfEAPRMbA7RLfm79fbmwar5B+rgIfZG3x53bVGlFxtpAFVAQ3AmfnYkA/DPfZWr7xUxJD/cS0aL65xkDzIH+03dHn6CUfIa8tCkQAPJNPOHv42fnzX339AdGgh95XD24aH1vTiTdfFonhbR5SXyo/Scl1IJCo5pa7ofkHuGRIh5qpwhB/PKA52vC+zBof72TR/o8ONV6N6eSH69lfhTOyhih9+3dJSWAbRdZSzleJTYUdnSAW7sEllEojG2r26rvr9066rXbQbuuyuScxYJt7t+Rv9SL7uK3+auIt4tDGZBC4sqOLl392q8/wqtJnB0pnsbBAnNbjPL++Xfcil6G9D7Mj5eX2zW17H5/Nn7aCGJ0h8YN/aEVFw3zBSrjkfDL4lpEZ51rPejQF/1FiVj5OoR4rfkfaXYFmWmNRO4J7VefWYpGENQhoRHjWOh9Jb1kVqU4SiygID/5fB9R2F0Q+4RdXTuBznLozODZa4phYT4O6476lzP02FPHP88QJ0zEcFjGviIQrLORIaJh4ekZZqzLe3sScH2FKAlrFiN56nb1H6TX04CTxL3P2Zi9PRSZOVmJ90t6rrsl3cjzT/KDecgZvl96tzZs+fzuegbvmbvoIG03NV/bi+jXGMmTPC4=
